### ISSUE TITLE
Create release `v24.0.0-rc.1.2023.05.03-detach`

### ISSUE THREAD

**Issue by parisk** [withlogicco/docker-cli#2]
### Description

Let's create a release in our repo, where we can upload the binaries from https://github.com/gmargaritis/cli/pull/1, so we can use them internally in our workflows.

### To do

- [x] Create release `2023.05.03-master.withlogicco.detach`
- [x] Upload Docker CLI binaries (requirement: Linux AMD64)

**Comment by gmargaritis** [comment]
Released: https://github.com/withlogicco/docker-cli/releases/tag/2023.05.03-master.withlogicco.detach
